addSbtPlugin("org.typelevel" % "sbt-tpolecat" % "0.5.0")
addSbtPlugin("org.scala-native" % "sbt-scala-native" % "0.4.17")
addSbtPlugin("com.indoorvivants" % "bindgen-sbt-plugin" % "0.1.4")
addSbtPlugin("com.indoorvivants.vcpkg" % "sbt-vcpkg-native" % "0.0.20")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
